package com.workorder.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/*
 * Полные тональные схемы Material 3 для пресетов оформления.
 * Значения построены по тональным рядам M3 (тон 40 — primary light, 80 — primary dark и т.д.).
 */

// ===================== САПФИР (DEFAULT) =====================

val IndigoLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF415F91),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD6E3FF),
    onPrimaryContainer = Color(0xFF001B3E),
    secondary = Color(0xFF565F71),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDAE2F9),
    onSecondaryContainer = Color(0xFF131C2B),
    tertiary = Color(0xFF705575),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFAD8FD),
    onTertiaryContainer = Color(0xFF28132E),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF9F9FF),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFF9F9FF),
    onSurface = Color(0xFF191C20),
    surfaceVariant = Color(0xFFE0E2EC),
    onSurfaceVariant = Color(0xFF44474E),
    outline = Color(0xFF74777F),
    outlineVariant = Color(0xFFC4C6D0),
    inversePrimary = Color(0xFFAAC7FF),
    inverseSurface = Color(0xFF2E3036),
    inverseOnSurface = Color(0xFFF0F0F7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F3FA),
    surfaceContainer = Color(0xFFEDEDF4),
    surfaceContainerHigh = Color(0xFFE7E8EE),
    surfaceContainerHighest = Color(0xFFE2E2E9)
)

val IndigoDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFAAC7FF),
    onPrimary = Color(0xFF0A305F),
    primaryContainer = Color(0xFF294777),
    onPrimaryContainer = Color(0xFFD6E3FF),
    secondary = Color(0xFFBEC6DC),
    onSecondary = Color(0xFF283141),
    secondaryContainer = Color(0xFF3E4759),
    onSecondaryContainer = Color(0xFFDAE2F9),
    tertiary = Color(0xFFDDBCE0),
    onTertiary = Color(0xFF3F2844),
    tertiaryContainer = Color(0xFF573E5C),
    onTertiaryContainer = Color(0xFFFAD8FD),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF111318),
    onBackground = Color(0xFFE2E2E9),
    surface = Color(0xFF111318),
    onSurface = Color(0xFFE2E2E9),
    surfaceVariant = Color(0xFF44474E),
    onSurfaceVariant = Color(0xFFC4C6D0),
    outline = Color(0xFF8E9099),
    outlineVariant = Color(0xFF44474E),
    inversePrimary = Color(0xFF415F91),
    inverseSurface = Color(0xFFE2E2E9),
    inverseOnSurface = Color(0xFF2E3036),
    surfaceContainerLowest = Color(0xFF0C0E13),
    surfaceContainerLow = Color(0xFF191C20),
    surfaceContainer = Color(0xFF1D2024),
    surfaceContainerHigh = Color(0xFF282A2F),
    surfaceContainerHighest = Color(0xFF33353A)
)

// ===================== БИРЮЗА (OCEAN) =====================

val OceanLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF006A6A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF9CF1F0),
    onPrimaryContainer = Color(0xFF002020),
    secondary = Color(0xFF4A6363),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCCE8E7),
    onSecondaryContainer = Color(0xFF051F1F),
    tertiary = Color(0xFF4B607C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD3E4FF),
    onTertiaryContainer = Color(0xFF041C35),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF4FBFA),
    onBackground = Color(0xFF161D1D),
    surface = Color(0xFFF4FBFA),
    onSurface = Color(0xFF161D1D),
    surfaceVariant = Color(0xFFDAE5E4),
    onSurfaceVariant = Color(0xFF3F4948),
    outline = Color(0xFF6F7978),
    outlineVariant = Color(0xFFBEC9C8),
    inversePrimary = Color(0xFF80D5D4),
    inverseSurface = Color(0xFF2B3232),
    inverseOnSurface = Color(0xFFECF2F1),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEEF5F4),
    surfaceContainer = Color(0xFFE8EFEE),
    surfaceContainerHigh = Color(0xFFE2E9E8),
    surfaceContainerHighest = Color(0xFFDCE3E2)
)

val OceanDark: ColorScheme = darkColorScheme(
    primary = Color(0xFF80D5D4),
    onPrimary = Color(0xFF003737),
    primaryContainer = Color(0xFF004F4F),
    onPrimaryContainer = Color(0xFF9CF1F0),
    secondary = Color(0xFFB0CCCB),
    onSecondary = Color(0xFF1B3534),
    secondaryContainer = Color(0xFF324B4A),
    onSecondaryContainer = Color(0xFFCCE8E7),
    tertiary = Color(0xFFB3C8E8),
    onTertiary = Color(0xFF1C314B),
    tertiaryContainer = Color(0xFF334863),
    onTertiaryContainer = Color(0xFFD3E4FF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0E1515),
    onBackground = Color(0xFFDCE3E2),
    surface = Color(0xFF0E1515),
    onSurface = Color(0xFFDCE3E2),
    surfaceVariant = Color(0xFF3F4948),
    onSurfaceVariant = Color(0xFFBEC9C8),
    outline = Color(0xFF899392),
    outlineVariant = Color(0xFF3F4948),
    inversePrimary = Color(0xFF006A6A),
    inverseSurface = Color(0xFFDCE3E2),
    inverseOnSurface = Color(0xFF2B3232),
    surfaceContainerLowest = Color(0xFF091010),
    surfaceContainerLow = Color(0xFF161D1D),
    surfaceContainer = Color(0xFF1A2121),
    surfaceContainerHigh = Color(0xFF242B2B),
    surfaceContainerHighest = Color(0xFF2F3636)
)

// ===================== ХВОЯ (FOREST) =====================

val ForestLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF2F6B4F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB3F1D0),
    onPrimaryContainer = Color(0xFF002113),
    secondary = Color(0xFF4E6358),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD0E8D9),
    onSecondaryContainer = Color(0xFF0B1F15),
    tertiary = Color(0xFF3D6372),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFC1E8FA),
    onTertiaryContainer = Color(0xFF001F29),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF5FBF6),
    onBackground = Color(0xFF171D19),
    surface = Color(0xFFF5FBF6),
    onSurface = Color(0xFF171D19),
    surfaceVariant = Color(0xFFDCE5DD),
    onSurfaceVariant = Color(0xFF404942),
    outline = Color(0xFF707972),
    outlineVariant = Color(0xFFC0C9C1),
    inversePrimary = Color(0xFF97D5B4),
    inverseSurface = Color(0xFF2C322E),
    inverseOnSurface = Color(0xFFECF2ED),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5F0),
    surfaceContainer = Color(0xFFE9EFEA),
    surfaceContainerHigh = Color(0xFFE3E9E4),
    surfaceContainerHighest = Color(0xFFDDE4DE)
)

val ForestDark: ColorScheme = darkColorScheme(
    primary = Color(0xFF97D5B4),
    onPrimary = Color(0xFF003823),
    primaryContainer = Color(0xFF105138),
    onPrimaryContainer = Color(0xFFB3F1D0),
    secondary = Color(0xFFB4CCBD),
    onSecondary = Color(0xFF20352A),
    secondaryContainer = Color(0xFF374B40),
    onSecondaryContainer = Color(0xFFD0E8D9),
    tertiary = Color(0xFFA5CDDE),
    onTertiary = Color(0xFF073542),
    tertiaryContainer = Color(0xFF244C59),
    onTertiaryContainer = Color(0xFFC1E8FA),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F1511),
    onBackground = Color(0xFFDDE4DE),
    surface = Color(0xFF0F1511),
    onSurface = Color(0xFFDDE4DE),
    surfaceVariant = Color(0xFF404942),
    onSurfaceVariant = Color(0xFFC0C9C1),
    outline = Color(0xFF8A938B),
    outlineVariant = Color(0xFF404942),
    inversePrimary = Color(0xFF2F6B4F),
    inverseSurface = Color(0xFFDDE4DE),
    inverseOnSurface = Color(0xFF2C322E),
    surfaceContainerLowest = Color(0xFF0A100C),
    surfaceContainerLow = Color(0xFF171D19),
    surfaceContainer = Color(0xFF1B211D),
    surfaceContainerHigh = Color(0xFF252B27),
    surfaceContainerHighest = Color(0xFF303632)
)

// ===================== ЯНТАРЬ (AMBER) =====================

val AmberLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF8B5000),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDCBE),
    onPrimaryContainer = Color(0xFF2D1600),
    secondary = Color(0xFF725A42),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDCBE),
    onSecondaryContainer = Color(0xFF291806),
    tertiary = Color(0xFF58633A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFDCE8B4),
    onTertiaryContainer = Color(0xFF161E01),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFFF8F4),
    onBackground = Color(0xFF221A11),
    surface = Color(0xFFFFF8F4),
    onSurface = Color(0xFF221A11),
    surfaceVariant = Color(0xFFF2DFD1),
    onSurfaceVariant = Color(0xFF51453A),
    outline = Color(0xFF837468),
    outlineVariant = Color(0xFFD5C3B5),
    inversePrimary = Color(0xFFFFB870),
    inverseSurface = Color(0xFF382F25),
    inverseOnSurface = Color(0xFFFEEEDF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF1E6),
    surfaceContainer = Color(0xFFFBEBDD),
    surfaceContainerHigh = Color(0xFFF5E5D7),
    surfaceContainerHighest = Color(0xFFF0E0D2)
)

val AmberDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB870),
    onPrimary = Color(0xFF4A2800),
    primaryContainer = Color(0xFF693C00),
    onPrimaryContainer = Color(0xFFFFDCBE),
    secondary = Color(0xFFE1C1A4),
    onSecondary = Color(0xFF402C18),
    secondaryContainer = Color(0xFF59422C),
    onSecondaryContainer = Color(0xFFFFDCBE),
    tertiary = Color(0xFFC0CC9A),
    onTertiary = Color(0xFF2B3410),
    tertiaryContainer = Color(0xFF414B24),
    onTertiaryContainer = Color(0xFFDCE8B4),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF19120A),
    onBackground = Color(0xFFF0E0D2),
    surface = Color(0xFF19120A),
    onSurface = Color(0xFFF0E0D2),
    surfaceVariant = Color(0xFF51453A),
    onSurfaceVariant = Color(0xFFD5C3B5),
    outline = Color(0xFF9D8E81),
    outlineVariant = Color(0xFF51453A),
    inversePrimary = Color(0xFF8B5000),
    inverseSurface = Color(0xFFF0E0D2),
    inverseOnSurface = Color(0xFF382F25),
    surfaceContainerLowest = Color(0xFF130D06),
    surfaceContainerLow = Color(0xFF221A11),
    surfaceContainer = Color(0xFF261E15),
    surfaceContainerHigh = Color(0xFF31281F),
    surfaceContainerHighest = Color(0xFF3D3329)
)

// ===================== СЛИВА (LAVENDER) =====================

val LavenderLight: ColorScheme = lightColorScheme(
    primary = Color(0xFF73558D),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF1DAFF),
    onPrimaryContainer = Color(0xFF2B0E46),
    secondary = Color(0xFF665A70),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEDDEF7),
    onSecondaryContainer = Color(0xFF21182A),
    tertiary = Color(0xFF805158),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9DD),
    onTertiaryContainer = Color(0xFF321017),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFCF8FF),
    onBackground = Color(0xFF1D1B20),
    surface = Color(0xFFFCF8FF),
    onSurface = Color(0xFF1D1B20),
    surfaceVariant = Color(0xFFE8E0E9),
    onSurfaceVariant = Color(0xFF4A454D),
    outline = Color(0xFF7B757D),
    outlineVariant = Color(0xFFCCC4CD),
    inversePrimary = Color(0xFFDFB8F9),
    inverseSurface = Color(0xFF322F35),
    inverseOnSurface = Color(0xFFF5EFF7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F2FA),
    surfaceContainer = Color(0xFFF1ECF4),
    surfaceContainerHigh = Color(0xFFEBE6EE),
    surfaceContainerHighest = Color(0xFFE5E1E8)
)

val LavenderDark: ColorScheme = darkColorScheme(
    primary = Color(0xFFDFB8F9),
    onPrimary = Color(0xFF42265D),
    primaryContainer = Color(0xFF5A3D74),
    onPrimaryContainer = Color(0xFFF1DAFF),
    secondary = Color(0xFFD1C2DB),
    onSecondary = Color(0xFF372C40),
    secondaryContainer = Color(0xFF4E4358),
    onSecondaryContainer = Color(0xFFEDDEF7),
    tertiary = Color(0xFFF2B7BE),
    onTertiary = Color(0xFF4B252B),
    tertiaryContainer = Color(0xFF663A41),
    onTertiaryContainer = Color(0xFFFFD9DD),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF151218),
    onBackground = Color(0xFFE5E1E8),
    surface = Color(0xFF151218),
    onSurface = Color(0xFFE5E1E8),
    surfaceVariant = Color(0xFF4A454D),
    onSurfaceVariant = Color(0xFFCCC4CD),
    outline = Color(0xFF958E97),
    outlineVariant = Color(0xFF4A454D),
    inversePrimary = Color(0xFF73558D),
    inverseSurface = Color(0xFFE5E1E8),
    inverseOnSurface = Color(0xFF322F35),
    surfaceContainerLowest = Color(0xFF100D13),
    surfaceContainerLow = Color(0xFF1D1B20),
    surfaceContainer = Color(0xFF211F24),
    surfaceContainerHigh = Color(0xFF2C292F),
    surfaceContainerHighest = Color(0xFF37343A)
)
